import Link from '@/components/site-link';
import { ArrowUpRight, ArrowDown, Ruler, Gem, Layers3 } from 'lucide-react';
export default function Home(){return <>
<section className="hero"><img src="/hero.webp" alt="Inspiração de cozinha contemporânea com ilha de pedra natural e marcenaria azul-marinho" fetchPriority="high"/><div className="hero-shade"/><div className="hero-copy"><p className="eyebrow">NATUREZA, DESIGN E PRECISÃO</p><h1>Transformamos<br/>pedras em<br/><span>projetos únicos.</span></h1><p className="hero-sub">Excelência esculpida em cada detalhe.</p><p className="hero-desc">Pedras naturais e superfícies selecionadas para dar vida ao seu próximo projeto.</p><div className="actions"><Link className="button" href="/materiais">Conheça nossos materiais <ArrowUpRight size={18}/></Link><Link className="button glass" href="/orcamento">Solicite seu orçamento <ArrowUpRight size={18}/></Link></div></div><a className="scroll-cue" href="#essencia"><ArrowDown size={16}/> ROLE PARA EXPLORAR</a><span className="hero-note">ARQUITETURA QUE INSPIRA · IMAGEM CONCEITUAL</span></section>
<section className="benefits"><div><Gem/><span>Materiais selecionados<small>Beleza que vem da natureza.</small></span></div><div><Ruler/><span>Precisão em cada corte<small>Seu projeto, na medida certa.</small></span></div><div><Layers3/><span>Do início ao acabamento<small>Cuidado em todas as etapas.</small></span></div></section>
<section id="essencia" className="section intro reveal"><div><p className="eyebrow">A ESSÊNCIA ECONORTE</p><h2>Beleza natural.<br/>Precisão em<br/><span className="muted">cada detalhe.</span></h2></div><div className="intro-text"><p>Na Econorte, transformamos pedras naturais e superfícies tecnológicas em projetos exclusivos, unindo beleza, durabilidade e sofisticação.</p><p>Materiais selecionados, soluções personalizadas e atenção aos detalhes para ambientes residenciais e comerciais.</p><Link className="text-link" href="/a-econorte">Conheça a Econorte <ArrowUpRight size={20}/></Link></div></section>
<section className="section materials-section reveal"><div className="section-heading"><div><p className="eyebrow">MATÉRIA-PRIMA PARA SUAS IDEIAS</p><h2>Uma escolha natural.<br/>Infinitas possibilidades.</h2></div><Link className="text-link" href="/materiais">Explore os materiais <ArrowUpRight size={20}/></Link></div><div className="home-materials">{[['Mármores','Elegância em cada veio.','marmore-calcitico','marble'],['Granitos','Feitos para acompanhar a vida.','granito','granite'],['Superfícies','Design e tecnologia em harmonia.','lamina-sinterizada','surface']].map(([name,desc,slug,img],i)=><Link className="material-tile" href={'/materiais/'+slug} key={slug}><img src={'/materials/'+img+'.webp'} alt={name==='Superfícies'?'Ambiente conceitual com superfície clara':'Textura ilustrativa de '+name} loading="lazy"/><div><span className="tile-index">0{i+1}</span><h3>{name}</h3><p>{desc}</p><span className="circle-arrow"><ArrowUpRight/></span></div></Link>)}</div><div className="material-strip"><span>Também em nossa seleção</span><Link href="/materiais/quartzito">Quartzito ↗</Link><Link href="/materiais/quartzo">Quartzo ↗</Link><Link href="/materiais/nanoglass">Nanoglass ↗</Link><Link href="/materiais/basalto">Basalto ↗</Link></div></section>
<section className="section environments reveal"><div className="section-heading"><div><p className="eyebrow">SEU AMBIENTE, SUA ESSÊNCIA</p><h2>Onde será seu<br/>próximo projeto?</h2></div><p>Da primeira ideia ao último detalhe,<br/>uma superfície para cada ambiente.</p></div><div className="environment-grid">{['Cozinhas','Banheiros','Áreas gourmet','Áreas externas','Fachadas','Ambientes comerciais'].map((n,i)=><Link href={'/projetos?ambiente='+encodeURIComponent(n)} key={n} className="environment"><img src={i===1?'/bathroom.webp':i>2?'/exterior.webp':'/hero.webp'} alt={'Inspiração para '+n.toLowerCase()} loading="lazy"/><div><small>0{i+1} / INSPIRAÇÕES</small><h3>{n}</h3><ArrowUpRight/></div></Link>)}</div></section>
<section className="section process reveal"><p className="eyebrow">CUIDADO QUE VOCÊ VÊ. QUALIDADE QUE VOCÊ SENTE.</p><h2>Do projeto à instalação.</h2><div className="process-grid">{['Escolha do material','Medição','Produção','Acabamento','Instalação'].map((n,i)=><div key={n}><span>0{i+1}</span><h3>{n}</h3><p>{['A superfície que combina com sua ideia.','Cada dimensão faz a diferença.','Seu projeto começa a ganhar forma.','Detalhes que valorizam o resultado.','O encontro entre a pedra e o ambiente.'][i]}</p></div>)}</div></section>
<section className="cta-section reveal"><p className="eyebrow">VAMOS CRIAR ALGO ÚNICO?</p><h2>Seu próximo projeto<br/>começa com uma conversa.</h2><Link className="button" href="/orcamento">Solicite seu orçamento <ArrowUpRight size={19}/></Link></section>
</>}
