'use client';
import Link from '@/components/site-link';
import {usePathname} from 'next/navigation';
import {useEffect,useState,useRef} from 'react';
import {ArrowUpRight, Menu, X, MessageCircle, Camera} from 'lucide-react';
const links=[['/','Início'],['/a-econorte','A Econorte'],['/materiais','Materiais'],['/projetos','Projetos'],['/inspiracoes','Inspirações'],['/contato','Contato']];
export const whatsapp='https://wa.me/5527988778389?text='+encodeURIComponent('Olá! Conheci a Econorte pelo site e gostaria de solicitar um orçamento.');
export default function SiteShell({children}:{children:React.ReactNode}){const path=usePathname();const[open,setOpen]=useState(false);const menuButton=useRef<HTMLButtonElement>(null);useEffect(()=>{if(!open)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);menuButton.current?.focus()}};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close)},[open]);useEffect(()=>{setOpen(false);const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:0.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));return()=>observer.disconnect()},[path]);return <><a className="skip-link" href="#main">Pular para o conteúdo</a><header className="site-header"><Link href="/" aria-label="Econorte, início" className="brand"><img src="/logo-white.webp" alt="Econorte — Mármores e Granitos" width="210" height="54"/></Link><nav id="main-navigation" aria-label="Navegação principal" className={open?'nav open':'nav'}>{links.map(([url,title])=><Link href={url} key={url} aria-current={path===url?'page':undefined} className={path===url?'active':''}>{title}</Link>)}<span className="coming" title="Novidade Econorte. Em breve.">Tijolo ecológico<small>EM BREVE</small></span></nav><Link href="/orcamento" className="button header-cta">Seu orçamento <ArrowUpRight size={17}/></Link><button ref={menuButton} aria-controls="main-navigation" className="mobile-toggle" aria-label={open?'Fechar menu':'Abrir menu'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header><main id="main" key={path} className="page-enter">{children}</main><footer><div className="footer-main"><div><Link href="/"><img src="/logo-white.webp" width="250" height="65" alt="Econorte"/></Link><p>Excelência esculpida<br/>em cada detalhe.</p></div><div><small>EXPLORE</small>{links.slice(1).map(([url,title])=><Link key={url} href={url}>{title}</Link>)}</div><div><small>VAMOS CONVERSAR</small><a href={whatsapp} target="_blank" rel="noopener noreferrer">(27) 9 8877-8389 ↗</a><a href="https://www.instagram.com/econorte_marmoresegranitos/" target="_blank" rel="noopener noreferrer"><Camera size={18}/> @econorte_marmoresegranitos</a><Link href="/orcamento">Solicitar orçamento ↗</Link></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Econorte. Todos os direitos reservados.</span><span>Pedra. Arquitetura. Precisão.</span></div></footer><a className="whatsapp" href={whatsapp} target="_blank" rel="noopener noreferrer" aria-label="Conversar com a Econorte no WhatsApp"><MessageCircle size={25}/></a></>}

