export const materials=[
{slug:'marmore-calcitico',name:'Mármore calcítico',headline:'Elegância para ambientes internos.',description:'A beleza natural dos veios e o acabamento refinado fazem do mármore uma escolha marcante para espaços de contemplação e bem-estar.',image:'/materials/marble.webp',imageLabel:'Textura ilustrativa de mármore; composição a confirmar na seleção.',tags:['Veios naturais','Acabamento refinado','Uso interno','Cuidados com ácidos'],uses:['Banheiro'],applications:['Bancadas de banheiro','Lavabos','Revestimentos internos'],care:'É sensível a produtos ácidos e pode absorver líquidos. A seleção da chapa, a impermeabilização e a manutenção devem ser orientadas para cada aplicação.'},
{slug:'marmore-dolomitico',name:'Mármore dolomítico',headline:'Resistência aliada à sofisticação.',description:'Uma pedra natural de presença elegante, com variações únicas de cor e desenho. Uma seleção que valoriza a arquitetura e os detalhes do projeto.',image:'/materials/marble.webp',imageLabel:'Textura ilustrativa de mármore; composição a confirmar na seleção.',tags:['Pedra natural','Variações exclusivas','Estética sofisticada','Seleção técnica'],uses:['Banheiro','Cozinha','Área gourmet'],applications:['Bancadas','Ilhas','Revestimentos'],care:'O desempenho varia conforme a rocha e o acabamento. Para cozinhas e áreas gourmet, confirme com a equipe a adequação da chapa e os cuidados contra manchas e ácidos.'},
{slug:'basalto',name:'Basalto',headline:'Robustez para dentro e fora.',description:'A expressão sóbria da pedra natural em superfícies que dialogam com a arquitetura contemporânea. Uma opção para projetos que valorizam textura e presença.',image:'/exterior.webp',imageLabel:'Inspiração arquitetônica; material da imagem não especificado.',tags:['Pedra natural','Estética sóbria','Textura','Versatilidade'],uses:['Área externa','Fachada'],applications:['Pisos','Fachadas','Revestimentos externos'],care:'Para áreas externas e pisos, especifique um acabamento adequado ao uso e às condições de umidade. O basalto é uma rocha vulcânica, uma categoria diferente do mármore.'},
{slug:'granito',name:'Granito',headline:'Resistência para o dia a dia.',description:'Uma escolha versátil para ambientes que combinam uso frequente, praticidade e beleza natural. Sua granulação cria superfícies com identidade própria.',image:'/materials/granite.webp',imageLabel:'Textura ilustrativa de granito.',tags:['Uso diário','Pedra natural','Versatilidade','Granulação natural'],uses:['Cozinha','Banheiro','Área gourmet','Área externa','Fachada'],applications:['Bancadas de cozinha','Pias','Áreas gourmet','Ambientes comerciais'],care:'Utilize apoio para panelas quentes e produtos de limpeza suaves. A necessidade de impermeabilização depende da variedade e do acabamento.'},
{slug:'quartzito',name:'Quartzito',headline:'A beleza natural encontra a resistência.',description:'Veios expressivos e uma estrutura cristalina dão ao quartzito uma personalidade singular. Cada chapa revela uma composição que não se repete.',image:'/hero.webp',imageLabel:'Ambiente conceitual; consulte amostras reais de quartzito.',tags:['Pedra natural','Veios marcantes','Estrutura cristalina','Chapas únicas'],uses:['Cozinha','Banheiro','Área gourmet','Área externa'],applications:['Ilhas','Bancadas','Painéis','Revestimentos'],care:'A seleção deve considerar a variedade, a absorção e a aplicação. Consulte a equipe sobre proteção da superfície e manutenção.'},
{slug:'quartzo',name:'Quartzo',headline:'Design para ambientes contemporâneos.',description:'Uma superfície industrializada que oferece possibilidades de cores e desenhos para composições equilibradas, funcionais e contemporâneas.',image:'/materials/surface.webp',imageLabel:'Inspiração conceitual; consulte padrões reais de quartzo.',tags:['Superfície industrializada','Variedade de cores','Design uniforme','Uso interno'],uses:['Cozinha','Banheiro','Área gourmet'],applications:['Bancadas internas','Lavabos','Ilhas'],care:'Evite calor direto e exposição externa sem aprovação do fabricante. Use descansos para panelas e siga as orientações da marca escolhida.'},
{slug:'lamina-sinterizada',name:'Lâmina sinterizada',headline:'Tecnologia em grandes superfícies.',description:'Minerais processados sob alta pressão e temperatura dão origem a superfícies contemporâneas para projetos que pedem continuidade visual e precisão.',image:'/materials/surface.webp',imageLabel:'Inspiração conceitual; consulte padrões reais de lâminas.',tags:['Tecnologia mineral','Grandes formatos','Continuidade visual','Design contemporâneo'],uses:['Cozinha','Banheiro','Área gourmet','Área externa','Fachada'],applications:['Bancadas e ilhas','Paredes','Revestimentos','Fachadas'],care:'A espessura, o suporte e os detalhes de instalação devem seguir a ficha técnica do fabricante e as necessidades da aplicação.'},
{slug:'nanoglass',name:'Nanoglass',headline:'Branco absoluto. Presença essencial.',description:'Uma superfície industrializada de aspecto branco e luminoso, ideal para composições que valorizam linhas limpas e leveza visual.',image:'/bathroom.webp',imageLabel:'Inspiração de ambiente; não representa uma amostra de Nanoglass.',tags:['Superfície industrializada','Aspecto branco','Brilho','Composição minimalista'],uses:['Cozinha','Banheiro'],applications:['Bancadas','Lavabos','Revestimentos internos'],care:'Confirme composição, acabamento, limitações e recomendações de instalação na ficha técnica do produto selecionado.'}
];
export const projects=[
{slug:'cozinha-integrada',name:'O encontro entre pedra e madeira',environment:'Cozinhas',image:'/hero.webp',material:'marmore-dolomitico',description:'Uma ilha generosa organiza o espaço e aproxima os momentos de preparo e convivência. A pedra clara contrasta com a marcenaria profunda, enquanto a luz destaca cada linha.',application:'Bancada e ilha',finish:'Aspecto polido'},
{slug:'banheiro-contemporaneo',name:'Um refúgio de texturas naturais',environment:'Banheiros',image:'/bathroom.webp',material:'marmore-calcitico',description:'Tons naturais e superfícies contínuas criam um espaço acolhedor. A iluminação suave valoriza a textura da pedra e a composição do ambiente.',application:'Bancada e revestimento',finish:'A definir na seleção'},
{slug:'area-gourmet',name:'Feito para reunir',environment:'Áreas gourmet',image:'/hero.webp',material:'granito',description:'Uma proposta de integração que coloca a bancada no centro da convivência. Materiais de uso diário e proporções equilibradas inspiram um ambiente acolhedor.',application:'Bancada e apoio',finish:'A definir na seleção'},
{slug:'arquitetura-externa',name:'Arquitetura em diálogo com o entorno',environment:'Áreas externas',image:'/exterior.webp',material:'basalto',description:'Volumes contemporâneos e texturas naturais criam uma composição de presença discreta. A escolha do acabamento considera clima, umidade e manutenção.',application:'Pisos e revestimentos',finish:'A definir conforme o uso'},
{slug:'fachada-contemporanea',name:'Uma primeira impressão marcante',environment:'Fachadas',image:'/exterior.webp',material:'lamina-sinterizada',description:'Superfícies amplas e linhas precisas valorizam os volumes da fachada. A especificação deve considerar fixação, juntas e comportamento em áreas externas.',application:'Revestimento de fachada',finish:'Conforme ficha técnica'},
{slug:'espaco-comercial',name:'Identidade em cada superfície',environment:'Ambientes comerciais',image:'/bathroom.webp',material:'granito',description:'Uma referência de composição para espaços comerciais: superfícies bem escolhidas podem unir expressão visual, manutenção e uso frequente.',application:'Bancadas e revestimentos',finish:'A definir no projeto'}
];
export const articles=[
{slug:'pedra-para-bancada-de-cozinha',title:'Qual pedra escolher para a bancada de cozinha?',category:'Guia de materiais',image:'/hero.webp',paragraphs:[['Comece pela sua rotina','O uso do ambiente ajuda a orientar a escolha. Considere a frequência de preparo, contato com alimentos, facilidade de limpeza e o efeito visual que deseja criar.'],['Compare amostras reais','Granito, quartzito e superfícies industrializadas oferecem possibilidades distintas. A variedade específica e a ficha técnica são mais úteis que uma comparação baseada apenas no nome do material.'],['Pense nos detalhes','Defina cuba, recortes, espessura, bordas e apoios junto com a bancada. Traga as medidas e referências para a equipe Econorte avaliar o conjunto.']]},
{slug:'marmore-ou-granito',title:'Mármore ou granito: qual combina com seu projeto?',category:'Escolhas conscientes',image:'/materials/marble.webp',paragraphs:[['Duas expressões da natureza','O mármore costuma chamar atenção pelos veios; o granito, pela granulação. Cada chapa tem variações e deve ser vista como parte da composição do ambiente.'],['O ambiente orienta a decisão','Considere umidade, contato com alimentos e produtos, frequência de uso e manutenção. A indicação precisa depende da variedade escolhida e do acabamento.'],['Escolha com orientação','Leve suas referências e converse sobre o uso esperado. A seleção combina estética e análise técnica para chegar a uma solução adequada.']]},
{slug:'pedras-para-area-gourmet',title:'Pedras para uma área gourmet feita para reunir',category:'Ambientes',image:'/hero.webp',paragraphs:[['Integração com propósito','Uma bancada pode conectar preparo, apoio e convivência. Planeje circulação e pontos de uso antes de definir suas dimensões.'],['Atenção à exposição','Uma área coberta e protegida tem condições diferentes de um espaço exposto ao sol e à chuva. Informe essas características ao escolher a superfície.'],['Detalhes que completam','Preveja apoios para objetos quentes, cubas e encontros com outros materiais. Esses detalhes devem estar no projeto desde o início.']]},
{slug:'cozinhas-modernas',title:'Cozinhas modernas: equilíbrio entre pedra, madeira e luz',category:'Arquitetura',image:'/hero.webp',paragraphs:[['Uma paleta bem resolvida','A pedra pode ser o ponto de destaque de uma cozinha com marcenaria discreta. Ou assumir um papel sereno junto de cores mais marcantes.'],['Luz e textura','Observe as amostras sob a iluminação prevista. A luz natural e a artificial alteram a percepção de cor, brilho e profundidade.'],['Continuidade visual','Ilhas e painéis podem criar unidade, respeitando as dimensões das chapas, os encontros e as limitações de instalação.']]},
{slug:'pedras-para-banheiros',title:'Pedras naturais para banheiros com personalidade',category:'Ambientes',image:'/bathroom.webp',paragraphs:[['Acolhimento em cada escolha','Texturas naturais e cores equilibradas ajudam a criar um ambiente tranquilo. Bancadas e revestimentos podem conversar sem precisar ser idênticos.'],['Escolha o acabamento','O brilho e a textura influenciam a aparência e o cuidado diário. Em pisos, considere também umidade e segurança.'],['Planeje a manutenção','Converse com a equipe sobre limpeza e proteção. Prefira produtos adequados ao material e siga as orientações recebidas.']]},
{slug:'como-escolher-bancada',title:'Os detalhes que fazem a diferença na sua bancada',category:'Planejamento',image:'/materials/granite.webp',paragraphs:[['Meça antes de decidir','Uma medida inicial ajuda no orçamento; a medição técnica confirma as dimensões para produzir. Defina os equipamentos e as cubas que serão usados.'],['Desenhe os encontros','Bordas, frontões, juntas e apoios fazem parte do resultado. Pense na proporção e na rotina do ambiente.'],['Reúna referências','Envie plantas, imagens e suas prioridades. Com essas informações, a equipe pode orientar a escolha e a viabilidade do projeto.']]},
{slug:'tendencias-pedras-naturais',title:'A força atemporal das pedras naturais',category:'Inspiração',image:'/materials/marble.webp',paragraphs:[['Autenticidade dos desenhos','Veios, granulações e variações de cor tornam cada superfície singular. Valorize essas diferenças ao selecionar a chapa.'],['Composições que permanecem','Materiais naturais podem dialogar com madeira, metal e luz. O equilíbrio nasce das proporções e do cuidado com os detalhes.'],['Seu estilo em primeiro lugar','Mais que seguir uma tendência, escolha uma composição que faça sentido para seu espaço e sua rotina.']]}
];
